{{- range .Values.config.templates }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___{{ .name }}
rules:
{{.rules | toYaml}}
- {{ . | toYaml }}
{{ else }}
[]
{{- end }}
