# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: permission-manager

resources:
  - ../bases
  - clusterRolesSeed.yaml

images:
  - name: permission-manager
    newName: permission-manager
    newTag: latest

patchesStrategicMerge:
  - ingress.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pm.fip.dev
    target:
      kind: Ingress
      name: permission-manager

secretGenerator:
  - name: permission-manager
    behavior: replace
    envs:
      - config/dev.env
